# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proyecto1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(745, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("\n"
"QWidget\n"
"{background-image: url(:/images/images/madera.png);\n"
"}\n"
"\n"
"QLabel#tabacos{\n"
"color:black;\n"
"font-size:50px;\n"
"font-family: courier new;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#ornelas{\n"
"color:black;\n"
"font-size:50px;\n"
"font-family: courier new;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro2{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro3{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro4{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro5{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro6{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro7{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro8{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro9{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#puro10{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QLabel#bienvenido{\n"
"background:none;\n"
"font-size:15px;\n"
"}\n"
"\n"
"QGroupBox#puros{\n"
"border:none;\n"
"background:none;\n"
"}\n"
"\n"
"QGroupBox#puros2{\n"
"border:none;\n"
"background:none;\n"
"}")
        self.tab.setObjectName("tab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.puros = QtWidgets.QGroupBox(self.tab)
        self.puros.setTitle("")
        self.puros.setObjectName("puros")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.puros)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.puro5 = QtWidgets.QLabel(self.puros)
        self.puro5.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro5.setText("")
        self.puro5.setObjectName("puro5")
        self.horizontalLayout.addWidget(self.puro5)
        self.puro3 = QtWidgets.QLabel(self.puros)
        self.puro3.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro3.setText("")
        self.puro3.setObjectName("puro3")
        self.horizontalLayout.addWidget(self.puro3)
        self.puro4 = QtWidgets.QLabel(self.puros)
        self.puro4.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro4.setText("")
        self.puro4.setObjectName("puro4")
        self.horizontalLayout.addWidget(self.puro4)
        self.puro = QtWidgets.QLabel(self.puros)
        self.puro.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro.setText("")
        self.puro.setObjectName("puro")
        self.horizontalLayout.addWidget(self.puro)
        self.puro2 = QtWidgets.QLabel(self.puros)
        self.puro2.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro2.setText("")
        self.puro2.setObjectName("puro2")
        self.horizontalLayout.addWidget(self.puro2)
        self.gridLayout_16.addWidget(self.puros, 0, 0, 1, 1)
        self.tabacos = QtWidgets.QLabel(self.tab)
        self.tabacos.setAlignment(QtCore.Qt.AlignCenter)
        self.tabacos.setObjectName("tabacos")
        self.gridLayout_16.addWidget(self.tabacos, 1, 0, 1, 1)
        self.ornelas = QtWidgets.QLabel(self.tab)
        self.ornelas.setAlignment(QtCore.Qt.AlignCenter)
        self.ornelas.setObjectName("ornelas")
        self.gridLayout_16.addWidget(self.ornelas, 2, 0, 1, 1)
        self.puros2 = QtWidgets.QGroupBox(self.tab)
        self.puros2.setTitle("")
        self.puros2.setObjectName("puros2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.puros2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.puro7 = QtWidgets.QLabel(self.puros2)
        self.puro7.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro7.setText("")
        self.puro7.setObjectName("puro7")
        self.gridLayout_2.addWidget(self.puro7, 0, 0, 1, 1)
        self.puro8 = QtWidgets.QLabel(self.puros2)
        self.puro8.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro8.setText("")
        self.puro8.setObjectName("puro8")
        self.gridLayout_2.addWidget(self.puro8, 0, 1, 1, 1)
        self.puro6 = QtWidgets.QLabel(self.puros2)
        self.puro6.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro6.setText("")
        self.puro6.setObjectName("puro6")
        self.gridLayout_2.addWidget(self.puro6, 0, 2, 1, 1)
        self.puro9 = QtWidgets.QLabel(self.puros2)
        self.puro9.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro9.setText("")
        self.puro9.setObjectName("puro9")
        self.gridLayout_2.addWidget(self.puro9, 0, 3, 1, 1)
        self.puro10 = QtWidgets.QLabel(self.puros2)
        self.puro10.setStyleSheet("image: url(:/prefijoNuevo/images/puro.png);")
        self.puro10.setText("")
        self.puro10.setObjectName("puro10")
        self.gridLayout_2.addWidget(self.puro10, 0, 4, 1, 1)
        self.gridLayout_16.addWidget(self.puros2, 3, 0, 1, 1)
        self.bienvenido = QtWidgets.QLabel(self.tab)
        self.bienvenido.setAlignment(QtCore.Qt.AlignCenter)
        self.bienvenido.setObjectName("bienvenido")
        self.gridLayout_16.addWidget(self.bienvenido, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.lineEdit_buscar_inventario = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_buscar_inventario.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_buscar_inventario.setObjectName("lineEdit_buscar_inventario")
        self.gridLayout_13.addWidget(self.lineEdit_buscar_inventario, 0, 0, 1, 2)
        self.pushButton_modificar_inventario = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_modificar_inventario.setObjectName("pushButton_modificar_inventario")
        self.gridLayout_13.addWidget(self.pushButton_modificar_inventario, 2, 0, 1, 1)
        self.pushButton_eliminar_inventario = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_eliminar_inventario.setObjectName("pushButton_eliminar_inventario")
        self.gridLayout_13.addWidget(self.pushButton_eliminar_inventario, 2, 1, 1, 1)
        self.pushButton_buscar_inventario = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_buscar_inventario.setObjectName("pushButton_buscar_inventario")
        self.gridLayout_13.addWidget(self.pushButton_buscar_inventario, 1, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_10, 4, 0, 1, 2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEdit_cantidad_inventario = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_cantidad_inventario.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_cantidad_inventario.setObjectName("lineEdit_cantidad_inventario")
        self.gridLayout_12.addWidget(self.lineEdit_cantidad_inventario, 2, 0, 1, 1)
        self.lineEdit_agregar_inventario = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_agregar_inventario.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_agregar_inventario.setObjectName("lineEdit_agregar_inventario")
        self.gridLayout_12.addWidget(self.lineEdit_agregar_inventario, 1, 0, 1, 2)
        self.lineEdit_precio_inventario = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_precio_inventario.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_precio_inventario.setObjectName("lineEdit_precio_inventario")
        self.gridLayout_12.addWidget(self.lineEdit_precio_inventario, 2, 1, 1, 1)
        self.pushButton_agregar_inventario = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_agregar_inventario.setObjectName("pushButton_agregar_inventario")
        self.gridLayout_12.addWidget(self.pushButton_agregar_inventario, 3, 0, 1, 2)
        self.gridLayout_9.addWidget(self.groupBox_9, 5, 0, 1, 2)
        self.tableWidget_inventario = QtWidgets.QTableWidget(self.groupBox_7)
        self.tableWidget_inventario.setObjectName("tableWidget_inventario")
        self.tableWidget_inventario.setColumnCount(0)
        self.tableWidget_inventario.setRowCount(0)
        self.gridLayout_9.addWidget(self.tableWidget_inventario, 0, 0, 1, 2)
        self.pushButton_ver_inventario = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_ver_inventario.setObjectName("pushButton_ver_inventario")
        self.gridLayout_9.addWidget(self.pushButton_ver_inventario, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_7, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.tableWidget_pedidos = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableWidget_pedidos.setObjectName("tableWidget_pedidos")
        self.tableWidget_pedidos.setColumnCount(0)
        self.tableWidget_pedidos.setRowCount(0)
        self.gridLayout_11.addWidget(self.tableWidget_pedidos, 0, 0, 1, 2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_ver_pedidos = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_ver_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ver_pedidos.setObjectName("lineEdit_ver_pedidos")
        self.gridLayout_14.addWidget(self.lineEdit_ver_pedidos, 0, 0, 1, 1)
        self.pushButton_ver_pedidos = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_ver_pedidos.setObjectName("pushButton_ver_pedidos")
        self.gridLayout_14.addWidget(self.pushButton_ver_pedidos, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_fecha_entrega_pedidos = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_fecha_entrega_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fecha_entrega_pedidos.setObjectName("lineEdit_fecha_entrega_pedidos")
        self.gridLayout_15.addWidget(self.lineEdit_fecha_entrega_pedidos, 2, 1, 1, 1)
        self.pushButton_agregar_pedidos = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_agregar_pedidos.setObjectName("pushButton_agregar_pedidos")
        self.gridLayout_15.addWidget(self.pushButton_agregar_pedidos, 4, 0, 1, 2)
        self.lineEdit_nombre_cliente_pedidos = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_nombre_cliente_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_nombre_cliente_pedidos.setObjectName("lineEdit_nombre_cliente_pedidos")
        self.gridLayout_15.addWidget(self.lineEdit_nombre_cliente_pedidos, 3, 0, 1, 1)
        self.lineEdit_fecha_pedidos = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_fecha_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fecha_pedidos.setObjectName("lineEdit_fecha_pedidos")
        self.gridLayout_15.addWidget(self.lineEdit_fecha_pedidos, 2, 0, 1, 1)
        self.lineEdit_telefono_cliente_pedidos = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_telefono_cliente_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_telefono_cliente_pedidos.setObjectName("lineEdit_telefono_cliente_pedidos")
        self.gridLayout_15.addWidget(self.lineEdit_telefono_cliente_pedidos, 3, 1, 1, 1)
        self.lineEdit_agregar_pedidos = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_agregar_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_agregar_pedidos.setObjectName("lineEdit_agregar_pedidos")
        self.gridLayout_15.addWidget(self.lineEdit_agregar_pedidos, 1, 0, 1, 1)
        self.lineEdit_cantidad_pedidos = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_cantidad_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_cantidad_pedidos.setObjectName("lineEdit_cantidad_pedidos")
        self.gridLayout_15.addWidget(self.lineEdit_cantidad_pedidos, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_12, 2, 0, 1, 2)
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_buscar_pedidos = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_buscar_pedidos.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_buscar_pedidos.setObjectName("lineEdit_buscar_pedidos")
        self.gridLayout_4.addWidget(self.lineEdit_buscar_pedidos, 0, 0, 1, 2)
        self.pushButton_modificar_pedidos = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_modificar_pedidos.setObjectName("pushButton_modificar_pedidos")
        self.gridLayout_4.addWidget(self.pushButton_modificar_pedidos, 2, 0, 1, 1)
        self.pushButton_eliminar_pedidos = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_eliminar_pedidos.setObjectName("pushButton_eliminar_pedidos")
        self.gridLayout_4.addWidget(self.pushButton_eliminar_pedidos, 2, 1, 1, 1)
        self.pushButton_buscar_pedidos = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_buscar_pedidos.setObjectName("pushButton_buscar_pedidos")
        self.gridLayout_4.addWidget(self.pushButton_buscar_pedidos, 1, 0, 1, 2)
        self.gridLayout_11.addWidget(self.groupBox_13, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableWidget_ventas = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_ventas.setObjectName("tableWidget_ventas")
        self.tableWidget_ventas.setColumnCount(0)
        self.tableWidget_ventas.setRowCount(0)
        self.gridLayout_7.addWidget(self.tableWidget_ventas, 0, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_ver_ventas = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ver_ventas.setObjectName("pushButton_ver_ventas")
        self.gridLayout_10.addWidget(self.pushButton_ver_ventas, 1, 0, 1, 1)
        self.lineEdit_ver_ventas = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_ver_ventas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_ver_ventas.setObjectName("lineEdit_ver_ventas")
        self.gridLayout_10.addWidget(self.lineEdit_ver_ventas, 0, 0, 1, 1)
        self.pushButton_ver_total_ventas = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ver_total_ventas.setObjectName("pushButton_ver_total_ventas")
        self.gridLayout_10.addWidget(self.pushButton_ver_total_ventas, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_cantidad_ventas = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_cantidad_ventas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_cantidad_ventas.setObjectName("lineEdit_cantidad_ventas")
        self.gridLayout_6.addWidget(self.lineEdit_cantidad_ventas, 2, 0, 1, 1)
        self.lineEdit_agregar_ventas = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_agregar_ventas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_agregar_ventas.setObjectName("lineEdit_agregar_ventas")
        self.gridLayout_6.addWidget(self.lineEdit_agregar_ventas, 1, 0, 1, 2)
        self.lineEdit_fecha_ventas = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_fecha_ventas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_fecha_ventas.setObjectName("lineEdit_fecha_ventas")
        self.gridLayout_6.addWidget(self.lineEdit_fecha_ventas, 2, 1, 1, 1)
        self.pushButton_agregar_ventas = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_agregar_ventas.setObjectName("pushButton_agregar_ventas")
        self.gridLayout_6.addWidget(self.pushButton_agregar_ventas, 3, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_6, 2, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_buscar_ventas = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_buscar_ventas.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_buscar_ventas.setObjectName("lineEdit_buscar_ventas")
        self.gridLayout_3.addWidget(self.lineEdit_buscar_ventas, 0, 0, 1, 2)
        self.pushButton_modificar_ventas = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_modificar_ventas.setObjectName("pushButton_modificar_ventas")
        self.gridLayout_3.addWidget(self.pushButton_modificar_ventas, 2, 0, 1, 1)
        self.pushButton_eliminar_ventas = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_eliminar_ventas.setObjectName("pushButton_eliminar_ventas")
        self.gridLayout_3.addWidget(self.pushButton_eliminar_ventas, 2, 1, 1, 1)
        self.pushButton_buscar_ventas = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_buscar_ventas.setObjectName("pushButton_buscar_ventas")
        self.gridLayout_3.addWidget(self.pushButton_buscar_ventas, 1, 0, 1, 2)
        self.gridLayout_7.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_17.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAgregar_productos = QtWidgets.QAction(MainWindow)
        self.actionAgregar_productos.setObjectName("actionAgregar_productos")
        self.actionVer_inventario = QtWidgets.QAction(MainWindow)
        self.actionVer_inventario.setObjectName("actionVer_inventario")
        self.actionModificar_datos = QtWidgets.QAction(MainWindow)
        self.actionModificar_datos.setObjectName("actionModificar_datos")
        self.actionBuscar_productos = QtWidgets.QAction(MainWindow)
        self.actionBuscar_productos.setObjectName("actionBuscar_productos")
        self.actionEliminar_productos = QtWidgets.QAction(MainWindow)
        self.actionEliminar_productos.setObjectName("actionEliminar_productos")
        self.actionAgregar_pedidos = QtWidgets.QAction(MainWindow)
        self.actionAgregar_pedidos.setObjectName("actionAgregar_pedidos")
        self.actionVer_pedidos = QtWidgets.QAction(MainWindow)
        self.actionVer_pedidos.setObjectName("actionVer_pedidos")
        self.actionModificar_pedidos = QtWidgets.QAction(MainWindow)
        self.actionModificar_pedidos.setObjectName("actionModificar_pedidos")
        self.actionBuscar_pedidos = QtWidgets.QAction(MainWindow)
        self.actionBuscar_pedidos.setObjectName("actionBuscar_pedidos")
        self.actionEliminar_pedidos = QtWidgets.QAction(MainWindow)
        self.actionEliminar_pedidos.setObjectName("actionEliminar_pedidos")
        self.actionAgregar_ventas = QtWidgets.QAction(MainWindow)
        self.actionAgregar_ventas.setObjectName("actionAgregar_ventas")
        self.actionVer_ventas = QtWidgets.QAction(MainWindow)
        self.actionVer_ventas.setObjectName("actionVer_ventas")
        self.actionBuscar_ventas = QtWidgets.QAction(MainWindow)
        self.actionBuscar_ventas.setObjectName("actionBuscar_ventas")
        self.actionCalcular_total = QtWidgets.QAction(MainWindow)
        self.actionCalcular_total.setObjectName("actionCalcular_total")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabacos.setText(_translate("MainWindow", "Tabacos"))
        self.ornelas.setText(_translate("MainWindow", "Ornelas"))
        self.bienvenido.setText(_translate("MainWindow", "Bienvenido, Administrador"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Inicio"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Buscar, eliminar y modificar"))
        self.lineEdit_buscar_inventario.setPlaceholderText(_translate("MainWindow", "Nombre del producto a buscar"))
        self.pushButton_modificar_inventario.setText(_translate("MainWindow", "Modificar producto"))
        self.pushButton_eliminar_inventario.setText(_translate("MainWindow", "Eliminar producto"))
        self.pushButton_buscar_inventario.setText(_translate("MainWindow", "Buscar producto"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Agregar"))
        self.lineEdit_cantidad_inventario.setPlaceholderText(_translate("MainWindow", "Cantidad disponible del producto"))
        self.lineEdit_agregar_inventario.setPlaceholderText(_translate("MainWindow", "Nombre del producto"))
        self.lineEdit_precio_inventario.setPlaceholderText(_translate("MainWindow", "Precio del producto"))
        self.pushButton_agregar_inventario.setText(_translate("MainWindow", "Agregar producto"))
        self.pushButton_ver_inventario.setText(_translate("MainWindow", "Ver inventario"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Inventario"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Ver"))
        self.lineEdit_ver_pedidos.setPlaceholderText(_translate("MainWindow", "Fecha de los pedidos"))
        self.pushButton_ver_pedidos.setText(_translate("MainWindow", "Ver pedidos"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Agregar"))
        self.lineEdit_fecha_entrega_pedidos.setPlaceholderText(_translate("MainWindow", "Fecha de entrega"))
        self.pushButton_agregar_pedidos.setText(_translate("MainWindow", "Agregar pedido"))
        self.lineEdit_nombre_cliente_pedidos.setPlaceholderText(_translate("MainWindow", "Nombre del cliente"))
        self.lineEdit_fecha_pedidos.setPlaceholderText(_translate("MainWindow", "Fecha del pedido"))
        self.lineEdit_telefono_cliente_pedidos.setPlaceholderText(_translate("MainWindow", "Teléfono del cliente"))
        self.lineEdit_agregar_pedidos.setPlaceholderText(_translate("MainWindow", "Nombre del producto pedido"))
        self.lineEdit_cantidad_pedidos.setPlaceholderText(_translate("MainWindow", "Cantidad pedida"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Buscar, eliminar y modificar"))
        self.lineEdit_buscar_pedidos.setPlaceholderText(_translate("MainWindow", "Número del pedido a buscar"))
        self.pushButton_modificar_pedidos.setText(_translate("MainWindow", "Modificar pedido"))
        self.pushButton_eliminar_pedidos.setText(_translate("MainWindow", "Eliminar pedido"))
        self.pushButton_buscar_pedidos.setText(_translate("MainWindow", "Buscar pedido"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Pedidos"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Ver"))
        self.pushButton_ver_ventas.setText(_translate("MainWindow", "Ver ventas"))
        self.lineEdit_ver_ventas.setPlaceholderText(_translate("MainWindow", "Fecha del día de las ventas"))
        self.pushButton_ver_total_ventas.setText(_translate("MainWindow", "Ver total"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Agregar"))
        self.lineEdit_cantidad_ventas.setPlaceholderText(_translate("MainWindow", "Cantidad vendida"))
        self.lineEdit_agregar_ventas.setPlaceholderText(_translate("MainWindow", "Nombre del producto vendido"))
        self.lineEdit_fecha_ventas.setPlaceholderText(_translate("MainWindow", "Fecha de la venta"))
        self.pushButton_agregar_ventas.setText(_translate("MainWindow", "Agregar venta"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Buscar, eliminar y modificar"))
        self.lineEdit_buscar_ventas.setPlaceholderText(_translate("MainWindow", "Número de la venta a buscar"))
        self.pushButton_modificar_ventas.setText(_translate("MainWindow", "Modificar venta"))
        self.pushButton_eliminar_ventas.setText(_translate("MainWindow", "Eliminar venta"))
        self.pushButton_buscar_ventas.setText(_translate("MainWindow", "Buscar venta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Ventas"))
        self.actionAgregar_productos.setText(_translate("MainWindow", "Agregar productos"))
        self.actionVer_inventario.setText(_translate("MainWindow", "Ver inventario"))
        self.actionModificar_datos.setText(_translate("MainWindow", "Modificar datos"))
        self.actionBuscar_productos.setText(_translate("MainWindow", "Buscar productos"))
        self.actionEliminar_productos.setText(_translate("MainWindow", "Eliminar productos"))
        self.actionAgregar_pedidos.setText(_translate("MainWindow", "Agregar pedidos"))
        self.actionVer_pedidos.setText(_translate("MainWindow", "Ver pedidos"))
        self.actionModificar_pedidos.setText(_translate("MainWindow", "Modificar pedidos"))
        self.actionBuscar_pedidos.setText(_translate("MainWindow", "Buscar pedidos"))
        self.actionEliminar_pedidos.setText(_translate("MainWindow", "Eliminar pedidos"))
        self.actionAgregar_ventas.setText(_translate("MainWindow", "Agregar ventas"))
        self.actionVer_ventas.setText(_translate("MainWindow", "Ver ventas"))
        self.actionBuscar_ventas.setText(_translate("MainWindow", "Buscar ventas"))
        self.actionCalcular_total.setText(_translate("MainWindow", "Calcular total"))
import source_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
